### ISSUE TITLE
Android issues starting from Ti SDK 5.1

### ISSUE THREAD

**Issue by Astrovic** [appcelerator-modules/ti.admob#45]
Since I updated to Ti SDK 5.1, Android ti.admob module no longer works. When I add the view to the window, win.add(adMobView); the app crashes :(

**Comment by hansemannn** [comment]
@ashcoding Looks like we need to recompile this one as well?

**Comment by ashcoding** [comment]
@hansemannn this might be another issue that is not related to recompilation.

**Comment by luiselizondo** [comment]
I'm having the same problem

**Comment by ashcoding** [comment]
@luiselizondo Could you describe what you are facing? Provide logs and info on what version of Android that faces this issue. Etc etc...

**Comment by luiselizondo** [comment]
Sure, this is the code I'm running

```
if(Ti.Platform.osname == "android") {
  // require AdMob
  // https://github.com/appcelerator-modules/ti.admob/issues/45
  var Admob = require('ti.admob');
    
  // then create an adMob view
  var adMobView = Admob.createView({
      publisherId:"PUBLISHER_ID",
      testing:false, // default is false
      //top: 10, //optional
      //left: 0, // optional
      //right: 0, // optional
      bottom: 0, // optional
      adBackgroundColor:"FF8855", // optional
      backgroundColorTop: "738000", //optional - Gradient background color at top
      borderColor: "#000000", // optional - Border color
      textColor: "#000000", // optional - Text color
      urlColor: "#00FF00", // optional - URL color
      linkColor: "#0000FF" //optional -  Link text color
      //primaryTextColor: "blue", // deprecated -- now maps to textColor
      //secondaryTextColor: "green" // deprecated -- now maps to linkColor      
  });
  
  $.androidAdView.add(adMobView);
}
```

On an .xml file I have:

```
 <View id="androidAdView" class="vgroup" platform="android">
 </View>
```

And basically I want to insert the admob view inside the androidAdView view.

I'm using the version ti.admob-android-2.1.6.zip downloaded from the android/dist directory and it is only activated for android. My tiapp.xml has the following code:

```
<android xmlns:android="http://schemas.android.com/apk/res/android"/>
<modules>
      <module platform="android">ti.admob</module>
</modules>
```

The application does not even start on the simulator, it crashes. I'm using Genymotion and it crashes on all the simulators I have.

The following logs are for running a Samsung Galaxy S5 4.4.4 API 19

```
-- Start application log -----------------------------------------------------
[INFO] :   TiApplication: (main) [0,0] checkpoint, app created.
[INFO] :   TiApplication: (main) [103,103] Titanium 5.1.2 (2015/12/16 19:00 ca822b2)
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 4.344MB for 552374-byte allocation
[INFO] :   TiApplication: (main) [339,442] Titanium Javascript runtime: v8
[WARN] :   V8Object: (KrollRuntimeThread) [29,471] Runtime disposed, cannot set property 'userAgent'
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null
[ERROR] :  E/        : UID 10058 asks for /proc/cpuinfo
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2
[INFO] :   dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method ti.modules.titanium.media.MediaModule.hasCameraPermission
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2neon
[ERROR] :  E/        : UID 10058 is not in ARM UID list files
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 33: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I
[INFO] :   dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method ti.modules.titanium.media.MediaModule.hasStoragePermission
[INFO] :   dalvikvm: Could not find method android.app.Activity.checkSelfPermission, referenced from method ti.modules.titanium.media.MediaModule.hasCameraPermissions
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 33: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 33: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I
[INFO] :   dalvikvm: Could not find method android.app.Activity.requestPermissions, referenced from method ti.modules.titanium.media.MediaModule.requestCameraPermissions
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 88: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
[INFO] :   dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onSearchRequested
[INFO] :   dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.internal.view.WindowCallbackWrapper.onWindowStartingActionMode
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
[WARN] :   dalvikvm: VFY: unable to resolve interface method 15045: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
[WARN] :   dalvikvm: VFY: unable to resolve interface method 15049: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 13.314MB for 6144012-byte allocation
[ERROR] :  E/        : UID 10058 asks for /proc/cpuinfo
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2neon
[ERROR] :  E/        : UID 10058 is not in ARM UID list files
[LiveView] Client connected
[INFO] :   dalvikvm: Could not find method android.view.ViewAnimationUtils.createCircularReveal, referenced from method org.appcelerator.titanium.proxy.TiViewProxy.handleHide
[WARN] :   dalvikvm: VFY: unable to resolve static method 14861: Landroid/view/ViewAnimationUtils;.createCircularReveal (Landroid/view/View;IIFF)Landroid/animation/Animator;
[INFO] :   dalvikvm: Could not find method android.view.ViewAnimationUtils.createCircularReveal, referenced from method org.appcelerator.titanium.proxy.TiViewProxy.handleShow
[WARN] :   dalvikvm: VFY: unable to resolve static method 14861: Landroid/view/ViewAnimationUtils;.createCircularReveal (Landroid/view/View;IIFF)Landroid/animation/Animator;
[ERROR] :  TiHTTPClient: (TiHttpClient-16) [1774,1774] HTTP Error (java.io.IOException): 404 : Not Found
[ERROR] :  TiHTTPClient: java.io.IOException: 404 : Not Found
[ERROR] :  TiHTTPClient: 	at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1223)
[ERROR] :  TiHTTPClient: 	at java.lang.Thread.run(Thread.java:841)
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity resume. activity = com.airescopio.www.AirescopioActivity@5286f084
[ERROR] :  E/        : UID 10058 asks for /proc/cpuinfo
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2
[ERROR] :  E/        : Unable to open file /data/data/.appwithABI2neon
[ERROR] :  E/        : UID 10058 is not in ARM UID list files
[WARN] :   TiUIScrollView: (main) [594,594] Scroll direction could not be determined based on the provided view properties. Default VERTICAL scroll direction being used. Use the 'scrollType' property to explicitly set the scrolling direction.
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 19.464MB for 2536932-byte allocation
[INFO] :   dalvikvm: Failed resolving Lcom/google/android/gms/ads/internal/zzl; interface 3437 'Lcom/google/android/gms/internal/zznw$zza;'
[WARN] :   dalvikvm: Link of class 'Lcom/google/android/gms/ads/internal/zzl;' failed
[INFO] :   dalvikvm: Could not find method com.google.android.gms.ads.internal.zzl.zzq, referenced from method com.google.android.gms.ads.internal.client.zzac.zzt
[WARN] :   dalvikvm: VFY: unable to resolve static method 18195: Lcom/google/android/gms/ads/internal/zzl;.zzq (Landroid/content/Context;)Lcom/google/android/gms/ads/internal/zzl;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8156 (common_google_play_services_unknown_issue) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8153 (common_google_play_services_notification_ticker) in Lcom/google/android/gms/R$string;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8132 (common_ic_googleplayservices) in Lcom/google/android/gms/R$drawable;
[WARN] :   dalvikvm: VFY: unable to resolve static field 8153 (common_google_play_services_notification_ticker) in Lcom/google/android/gms/R$string;
[INFO] :   dalvikvm: Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzh
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 592: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
[INFO] :   dalvikvm: DexOpt: unable to optimize static field ref 0x1fc3 at 0x66 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.zza
[INFO] :   dalvikvm: DexOpt: unable to optimize static field ref 0x1fe4 at 0x68 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.zza
[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
[WARN] :   GooglePlayServicesUtil: Google Play services is missing.
[INFO] :   dalvikvm: Failed resolving Lcom/google/android/gms/ads/internal/zzl; interface 3437 'Lcom/google/android/gms/internal/zznw$zza;'
[WARN] :   dalvikvm: Link of class 'Lcom/google/android/gms/ads/internal/zzl;' failed
[INFO] :   dalvikvm: Could not find method com.google.android.gms.ads.internal.zzl.zzq, referenced from method com.google.android.gms.ads.internal.zzb.zza
[WARN] :   dalvikvm: VFY: unable to resolve static method 18195: Lcom/google/android/gms/ads/internal/zzl;.zzq (Landroid/content/Context;)Lcom/google/android/gms/ads/internal/zzl;
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[INFO] :   dalvikvm: Failed resolving Lcom/google/android/gms/ads/internal/zzl; interface 3437 'Lcom/google/android/gms/internal/zznw$zza;'
[WARN] :   dalvikvm: Link of class 'Lcom/google/android/gms/ads/internal/zzl;' failed
[INFO] :   dalvikvm: Could not find method com.google.android.gms.ads.internal.zzl.zzq, referenced from method com.google.android.gms.ads.internal.zza.zza
[WARN] :   dalvikvm: VFY: unable to resolve static method 18195: Lcom/google/android/gms/ads/internal/zzl;.zzq (Landroid/content/Context;)Lcom/google/android/gms/ads/internal/zzl;
[INFO] :   dalvikvm: Failed resolving Lcom/google/android/gms/ads/internal/zzl; interface 3437 'Lcom/google/android/gms/internal/zznw$zza;'
[WARN] :   dalvikvm: Link of class 'Lcom/google/android/gms/ads/internal/zzl;' failed
[INFO] :   dalvikvm: Could not find method com.google.android.gms.ads.internal.zzl.zzq, referenced from method com.google.android.gms.ads.internal.zza.zza
[WARN] :   dalvikvm: VFY: unable to resolve static method 18195: Lcom/google/android/gms/ads/internal/zzl;.zzq (Landroid/content/Context;)Lcom/google/android/gms/ads/internal/zzl;
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[ERROR] :  dalvikvm: Could not find class 'com.google.android.gms.internal.zzan', referenced from method com.google.android.gms.ads.internal.zzp.<init>
[WARN] :   dalvikvm: VFY: unable to resolve new-instance 2902 (Lcom/google/android/gms/internal/zzan;) in Lcom/google/android/gms/ads/internal/zzp;
[INFO] :   dalvikvm: Failed resolving Lcom/google/android/gms/ads/internal/zzg; interface 2900 'Lcom/google/android/gms/internal/zzaj;'
[WARN] :   dalvikvm: Link of class 'Lcom/google/android/gms/ads/internal/zzg;' failed
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[INFO] :   dalvikvm: Could not find method com.google.android.gms.internal.zzan.zzc, referenced from method com.google.android.gms.internal.zzhl.zza
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 21115: Lcom/google/android/gms/internal/zzan;.zzc (Landroid/net/Uri;)Z
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa4d4ab20)
[ERROR] :  TiApplication: (main) [64,940] Sending event: exception on thread: main msg:java.lang.NoClassDefFoundError: com.google.android.gms.internal.zzan; Titanium 5.1.2,2015/12/16 19:00,ca822b2
[ERROR] :  TiApplication: java.lang.NoClassDefFoundError: com.google.android.gms.internal.zzan
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzp.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzp.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzb.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzc.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zze.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.client.zze.zza(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.client.zzy.zzcO(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.client.zzy.zza(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.AdView.loadAd(Unknown Source)
[ERROR] :  TiApplication: 	at ti.admob.View$2.run(View.java:81)
[ERROR] :  TiApplication: 	at android.app.Activity.runOnUiThread(Activity.java:4713)
[ERROR] :  TiApplication: 	at ti.admob.View.loadAd(View.java:69)
[ERROR] :  TiApplication: 	at ti.admob.View.createAdView(View.java:64)
[ERROR] :  TiApplication: 	at ti.admob.View.processProperties(View.java:135)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1209)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:505)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:496)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:474)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:512)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:496)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:474)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:512)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:496)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:474)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:512)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:496)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:474)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:512)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:496)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:474)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:675)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:569)
[ERROR] :  TiApplication: 	at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:237)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:33)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:508)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:601)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] :  TiApplication: 	at android.app.Activity.performCreate(Activity.java:5231)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callAc
[ERROR] :  TiApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:136)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5001)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
[ERROR] :  TiApplication: 	at dalvik.system.NativeStart.main(Native Method)
[WARN] :   TiVerify: (Timer-0) [4096,5036] Verifying module licenses...
[INFO] :   TiVerify: (Timer-0) [1691,6727] Succesfully verified module licenses
[INFO] :   Process: Sending signal. PID: 1661 SIG: 9
```

**Comment by luiselizondo** [comment]
@ashcoding any help that you can provide will be much appreciated

**Comment by ashcoding** [comment]
The logs looks bad. :( This is using Titanium SDK 5.1.0?

**Comment by luiselizondo** [comment]
@ashcoding These are the latests logs using SDK 5.3.1, Android tool-api-level 23 and ti.admob version 2.1.6

```
[INFO] :   dalvikvm: DexOpt: unable to optimize static field ref 0x1fc3 at 0x66 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.zza
[INFO] :   dalvikvm: DexOpt: unable to optimize static field ref 0x1fe4 at 0x68 in Lcom/google/android/gms/common/GooglePlayServicesUtil;.zza
[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
[WARN] :   GooglePlayServicesUtil: Google Play services is missing.
[INFO] :   Google Play Services is not installed/updated/available
[INFO] :   dalvikvm: Failed resolving Lcom/google/android/gms/ads/internal/zzl; interface 3444 'Lcom/google/android/gms/internal/zznw$zza;'
[WARN] :   dalvikvm: Link of class 'Lcom/google/android/gms/ads/internal/zzl;' failed
[INFO] :   dalvikvm: Could not find method com.google.android.gms.ads.internal.zzl.zzq, referenced from method com.google.android.gms.ads.internal.client.zzac.zzt
[WARN] :   dalvikvm: VFY: unable to resolve static method 18211: Lcom/google/android/gms/ads/internal/zzl;.zzq (Landroid/content/Context;)Lcom/google/android/gms/ads/internal/zzl;
[ERROR] :  GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
[WARN] :   GooglePlayServicesUtil: Google Play services is missing.
[INFO] :   dalvikvm: Failed resolving Lcom/google/android/gms/ads/internal/zzl; interface 3444 'Lcom/google/android/gms/internal/zznw$zza;'
[WARN] :   dalvikvm: Link of class 'Lcom/google/android/gms/ads/internal/zzl;' failed
[INFO] :   dalvikvm: Could not find method com.google.android.gms.ads.internal.zzl.zzq, referenced from method com.google.android.gms.ads.internal.zzb.zza
[WARN] :   dalvikvm: VFY: unable to resolve static method 18211: Lcom/google/android/gms/ads/internal/zzl;.zzq (Landroid/content/Context;)Lcom/google/android/gms/ads/internal/zzl;
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[INFO] :   dalvikvm: Failed resolving Lcom/google/android/gms/ads/internal/zzl; interface 3444 'Lcom/google/android/gms/internal/zznw$zza;'
[WARN] :   dalvikvm: Link of class 'Lcom/google/android/gms/ads/internal/zzl;' failed
[INFO] :   dalvikvm: Could not find method com.google.android.gms.ads.internal.zzl.zzq, referenced from method com.google.android.gms.ads.internal.zza.zza
[WARN] :   dalvikvm: VFY: unable to resolve static method 18211: Lcom/google/android/gms/ads/internal/zzl;.zzq (Landroid/content/Context;)Lcom/google/android/gms/ads/internal/zzl;
[INFO] :   dalvikvm: Failed resolving Lcom/google/android/gms/ads/internal/zzl; interface 3444 'Lcom/google/android/gms/internal/zznw$zza;'
[WARN] :   dalvikvm: Link of class 'Lcom/google/android/gms/ads/internal/zzl;' failed
[INFO] :   dalvikvm: Could not find method com.google.android.gms.ads.internal.zzl.zzq, referenced from method com.google.android.gms.ads.internal.zza.zza
[WARN] :   dalvikvm: VFY: unable to resolve static method 18211: Lcom/google/android/gms/ads/internal/zzl;.zzq (Landroid/content/Context;)Lcom/google/android/gms/ads/internal/zzl;
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[ERROR] :  dalvikvm: Could not find class 'com.google.android.gms.internal.zzan', referenced from method com.google.android.gms.ads.internal.zzp.<init>
[WARN] :   dalvikvm: VFY: unable to resolve new-instance 2909 (Lcom/google/android/gms/internal/zzan;) in Lcom/google/android/gms/ads/internal/zzp;
[INFO] :   dalvikvm: Failed resolving Lcom/google/android/gms/ads/internal/zzg; interface 2907 'Lcom/google/android/gms/internal/zzaj;'
[WARN] :   dalvikvm: Link of class 'Lcom/google/android/gms/ads/internal/zzg;' failed
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[INFO] :   dalvikvm: Could not find method com.google.android.gms.internal.zzan.zzc, referenced from method com.google.android.gms.internal.zzhl.zza
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 21131: Lcom/google/android/gms/internal/zzan;.zzc (Landroid/net/Uri;)Z
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[WARN] :   dalvikvm: VFY: unable to find class referenced in signature (Lcom/google/android/gms/internal/zzan;)
[WARN] :   dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa4cdfb20)
[ERROR] :  TiApplication: (main) [97,14138] Sending event: exception on thread: main msg:java.lang.NoClassDefFoundError: com.google.android.gms.internal.zzan; Titanium 5.3.1,2016/06/09 01:34,ee11b10
[ERROR] :  TiApplication: java.lang.NoClassDefFoundError: com.google.android.gms.internal.zzan
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzp.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzp.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzb.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zzc.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.zze.<init>(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.client.zze.zza(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.client.zzy.zzcO(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.internal.client.zzy.zza(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.ads.AdView.loadAd(Unknown Source)
[ERROR] :  TiApplication: 	at ti.admob.View$2.run(View.java:81)
[ERROR] :  TiApplication: 	at android.app.Activity.runOnUiThread(Activity.java:4713)
[ERROR] :  TiApplication: 	at ti.admob.View.loadAd(View.java:69)
[ERROR] :  TiApplication: 	at ti.admob.View.createAdView(View.java:64)
[ERROR] :  TiApplication: 	at ti.admob.View.processProperties(View.java:135)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1219)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:509)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:500)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:478)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:679)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:239)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:136)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5001)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
[ERROR] :  TiApplication:
```

**Comment by ashcoding** [comment]
I created a JIRA ticket here: https://github.com/appcelerator-modules/ti.admob/issues/45

**Comment by ashcoding** [comment]
My guess would be that something is not happy with this https://github.com/appcelerator-modules/ti.admob/tree/master/android/lib

The stripped version of Google Play was the major change in 2.1.6.

Are you able to use 2.1.5 without any issues?

**Comment by luiselizondo** [comment]
No. I can't make it work with 2.1.5 either

**Comment by ashcoding** [comment]
Same issues with 2.1.5?

**Comment by ashcoding** [comment]
[ti.admob-android-2.1.7.zip](https://github.com/appcelerator-modules/ti.admob/files/356708/ti.admob-android-2.1.7.zip)

I didn't do anything special with this. This is 2.1.6 that is recompiled and renamed 2.1.7. I didn't face any issues using this. Can't reproduce your error. Could you try it out?

Also, are they any other modules that you are using? Perhaps they could be contributing to this error?
Could you list out the other modules that are being used?

**Comment by luiselizondo** [comment]
No, it didn't work. I'm still getting the same error, which I think is because of: 

```[ERROR] :  TiApplication: (main) [69,3700] Sending event: exception on thread: main msg:java.lang.NoClassDefFoundError: com.google.android.gms.internal.zzan; Titanium 5.3.1,2016/06/09 01:34,ee11b10
```

and because of: `The Google Play services resources were not found`

I don't have any modules installed but ti.admob and ti.cloud. Am I missing something obvious? Like installing Google Play Services or a dependency of some kind?

**Comment by ashcoding** [comment]
I don't think you've done anything wrong...
I'll check with ti.cloud and ti.admob. Which version of ti.cloud is being used? The Google Play libs are inside the modules.

Really want to solve this.

**Comment by luiselizondo** [comment]
Latest, which I guess is 3.2.10 at the moment I'm writing this.

**Comment by ashcoding** [comment]
Thanks. I'll check this.

**Comment by wpjmurray** [comment]
Have there been any updates on this? I'm getting the same errors as luiselizondo, I'm using ti.admob but not ti.cloud (I am using a GCM module and a few others). I recently release a production version of my app and I'm seeing crashes related to the admob module for Android 6 devices.
